import Image from 'next/image'
import Link from 'next/link'
import logo from '../../public/logo.png';
import { NavBar } from './NavBar';
import './globals.css';
import 'normalize.css'
import style from './layout.module.scss';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body className={style.page}>
        <header>
          <Link href="/">
            <Image
              src={logo}
              alt="logo"
              width={30}
              height={30}
            />
          </Link>
        </header>
        {children}
        <NavBar />
      </body>
    </html>
  )
}
